#!/bin/sh

# using xidel to find new mac stuffs on nhattao.com
# nhattao "mac mini" 30 15000000 33000000 HoChiMinh
# nhattao "macbook pro 14" 30 15000000 36000000 HoChiMinh

QUERY="$1"
LAST_DAYS=$2
MIN_PRICE=$3
MAX_PRICE=$4
LOCATION=$5
SINCE=$(date -v -"$LAST_DAYS"d +%s)
ORDER_BY=date

DOMAIN="https://nhattao.com"
SEARCH_URL="$DOMAIN/search/search"

echo "————————————————————————————————————————————————————————————————————————————————"
echo ">: $QUERY | Last $LAST_DAYS days | Min Price: $MIN_PRICE | Max Price: $MAX_PRICE | Location: $LOCATION"
echo "————————————————————————————————————————————————————————————————————————————————"

TEMPLATE="string-join(('$DOMAIN/', //form[@class='tagView_formFilters']/@action), '')"
NEXT_URL=$(xidel -s \
  -d "keywords=$QUERY" \
  -d "date=$SINCE" \
  -d "nodes[]=483" \
  -d "child_nodes=1" \
  -d "order=$ORDER_BY" \
  -d "tinhte_classified_location=$LOCATION" \
  -d "tinhte_classified_status=0" \
  "$SEARCH_URL" -e "$TEMPLATE")

if [[ "$NEXT_URL" = "https://nhattao.com/" ]]; then
  exit;
else
  NEXT_URL="$NEXT_URL&min_price=$MIN_PRICE&max_price=$MAX_PRICE"
fi

TEMPLATE=$(cat <<EOF
<t:loop t:optional="true">
  <span class="classified_thread_list_price">{price:=normalize-space(.)}</span>
  <h3 class="title">{title := normalize-space(.)}</h3>
  <a>{links := string-join(("$DOMAIN", replace(@href, "\?(.*)", "")),"/")}</a>
  {headings := string-join((\$price, \$title), " | ")}
</t:loop>
EOF
)

# apply everything from xidel to $SHELL variables
eval $(xidel $NEXT_URL \
  --silent \
  --extract-include="headings,links" \
  --hide-variable-names \
  --extract "$TEMPLATE" \
  --output-format="bash")

# results
len=${#headings[@]}
for (( idx = 0; idx < len; idx++ ));
do
  echo "${headings[idx]}"
  echo "${links[idx]}\n"
done

