#!/bin/sh

# using xidel to find new mac stuffs on nhattao.com
# nhattao "mac mini" 30 15000000 33000000 HoChiMinh
# nhattao "macbook pro 14" 30 15000000 36000000 HoChiMinh

QUERY="${1:-'mac mini'}"
LAST_DAYS=${2:-14}
MAX_PRICE=${3:-100000000}
MIN_PRICE=${4:-0}
LOCATION=${5:-HoChiMinh} # use 0 for toan quoc
CATEGORY=${6:-0}
SINCE=$(date -v -"$LAST_DAYS"d +%s)
ORDER_BY=date

DOMAIN="https://nhattao.com"
SEARCH_URL="$DOMAIN/search/search"

echo "————————————————————————————————————————————————————————————————————————————————"
echo "> $QUERY | Last $LAST_DAYS days | Price: $MIN_PRICE - $MAX_PRICE | Location: $LOCATION"
echo "————————————————————————————————————————————————————————————————————————————————"

TEMPLATE="string-join(('$DOMAIN/', //form[@class='tagView_formFilters']/@action), '')"
NEXT_URL=$(xidel -s \
  -d "keywords=$QUERY" \
  -d "date=$SINCE" \
  -d "nodes[]=$CATEGORY" \
  -d "child_nodes=1" \
  -d "order=$ORDER_BY" \
  -d "tinhte_classified_location=$LOCATION" \
  -d "tinhte_classified_status=0" \
  "$SEARCH_URL" -e "$TEMPLATE")

if [[ "$NEXT_URL" = "https://nhattao.com/" ]]; then
  exit;
else
  NEXT_URL="$NEXT_URL&min_price=$MIN_PRICE&max_price=$MAX_PRICE"
fi

TEMPLATE=$(cat <<EOF
<t:loop t:optional="true">
  <span class="classified_thread_list_price">{prices := normalize-space(.)}</span>
  <h3 class="title">{titles := normalize-space(.)}</h3>
  <a>{links := string-join(("$DOMAIN", replace(@href, "\?(.*)", "")),"/")}</a>
  <abbr class="DateTime">{dates := @data-datestring}</abbr>
  <span class="locationPrefix prefix prefixPrimary">{locations := normalize-space(.)}</span>
</t:loop>
EOF
)

# apply everything from xidel to $SHELL variables
eval $(xidel $NEXT_URL \
  --silent \
  --extract-include="prices,titles,links,dates,locations" \
  --hide-variable-names \
  --extract "$TEMPLATE" \
  --output-format="bash")

# results
len=${#prices[@]}
for (( idx = 0; idx < len; idx++ ));
do
  echo "${prices[idx]} • ${titles[idx]}"
  echo "${locations[idx]} • ${dates[idx]} • ${links[idx]}\n"
done

